spring:
  application:
    name: service-zuul-server
server:
  port: 8005
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    products:
      service-id: service-products
      path: /api/products/**
    
    items:
      service-id: service-items
      path: /api/items/**
